### ISSUE TITLE
/newmaps should prompt in-game messages

### ISSUE THREAD

**Issue by BGMP** [ElMedievo-UdeC/PGM#4]
Given /newmaps is generally used for quickly loading maps while in-game, I find it that makes more sense to get in-game response outputs from when running it.

Reminder to look into this.

**Comment by KingOfSquares** [comment]
What do you want it to say, i can add that.

**Comment by BGMP** [comment]
Oh my, it's kingoftimesquares?!

I's thinking on probably the same output it currently logs to the console, but in-game.

I was also kind of unsure about if I wanted only the issuer to recieve the response or if it should be sent to the admin chat, what do you think?

Also thanks for showing interest! Might be a cool thing to bring to the mainstream when done!

**Comment by KingOfSquares** [comment]
I personally think it's cool with adminchat, but makes more sense to only send to the issuer.
`Maps reloaded by <player>` looks a little weird? 

I will wait for https://github.com/PGMDev/PGM/pull/503 to be merged before i do this.

**Comment by BGMP** [comment]
For further reference, I believe those messages can be found [here](https://github.com/ElMedievo-UdeC/PGM/blob/2dea71b061ea31afe8a44a769a694be2159d812c/core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java#L85)

**Comment by KingOfSquares** [comment]
> For further reference, I believe those messages can be found [here](https://github.com/ElMedievo-UdeC/PGM/blob/2dea71b061ea31afe8a44a769a694be2159d812c/core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java#L85)

Oh! THen i guess we can just use that, and send into adminchat because its fun??

**Comment by BGMP** [comment]
And yes, lets wait for that to be merged. Messages should likely be turned into translarables as well, not sure why they aren't already.



> > For further reference, I believe those messages can be found [here](https://github.com/ElMedievo-UdeC/PGM/blob/2dea71b061ea31afe8a44a769a694be2159d812c/core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java#L85)
> 
> Oh! THen i guess we can just use that, and send into adminchat because its fun??

Perhaps, yeah, it was my original thought lol

**Comment by KingOfSquares** [comment]
Hm, unsure about this. /newmaps currently **does** provide chat feedback in the form of (X new maps loaded) or whatever. Is there any point in adding more?

**Comment by BGMP** [comment]
@KingOfSquares oh, does it? When I tried it out by the time I opened this issue it did not. The idea was to add chat messages, not to add *more* chat messages.

Are you sure it provides in-game responses when using it? I recall it only prompting a console message.

**Comment by KingOfSquares** [comment]
Yes, I just tested this. Sends me a message, see (I think) https://github.com/KingOfSquares/PGM/blob/12e9e602e3b7b3064d8a302719f5f5d5d4885ab7/core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java#L85

**Comment by BGMP** [comment]
Those are logs, not in-game messages, or am I missing something?

**Comment by KingOfSquares** [comment]
https://github.com/kingofsquares/PGM/blob/12e9e602e3b7b3064d8a302719f5f5d5d4885ab7/core/src/main/java/tc/oc/pgm/map/MapLibraryImpl.java#L53

Passed in `PGMPlugin`

**Comment by KingOfSquares** [comment]
Something like this maybe? https://github.com/KingOfSquares/PGM/commit/f73d35b513326a8eaa750cfd5755aec1127df2f7
But with prettier colors and everything of course

**Comment by BGMP** [comment]
Do you have any in-game showcase?

**Comment by BGMP** [comment]
Should be fine now.
